/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;

/**
 *
 * @author daniel
 */
public class Aviso extends javax.swing.JFrame {

    /**
     * Creates new form Aviso
     */
    public Aviso() {
        initComponents();
        this.setTitle("Importante!");
        this.setLocationRelativeTo(null);
        javax.swing.JFrame f = this;  
        this.addWindowListener(new WindowAdapter() {
         
            @Override
            public void windowActivated(WindowEvent e){
                
               
                SwingWorker worker = new SwingWorker() {
                    
                    long tempo = System.currentTimeMillis() + 17500;
                            @Override  
                            protected Object doInBackground() throws Exception {  
                                System.gc();
                                
                                while(System.currentTimeMillis()<=tempo){
                                    Thread.sleep(5);
                                }
                                return null;  
                            }  

                            @Override
                            protected void done(){  
                               System.exit(0);  
                                //  
                                
                            }  
                        };
                        
                        worker.execute();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(25);
        jTextArea1.setRows(8);

        jTextArea1.setText("Esse Aplicativo serve apenas para estimativas!\n"+
                "Numa situação real os valores podem ser sensivelmente \n"+
                "alterados, pois esse aplicativo não leva em consideração \n"+
                "a Taxa TR, nem mesmo a Selic.\n\n"+
                "Esse aplicativo leva em consideração apenas a taxa de juros que é:\n"+
                "6% ao ano.\n\n"+
                "Atenção: Esse software não possui NENHUMA GARANTIA, e muito menos \n"+
                "a obrigação de funcionar de forma precisa!");

        jTextArea1.setAlignmentX(JTextArea.CENTER_ALIGNMENT);
        jTextArea1.setAlignmentY(JTextArea.CENTER_ALIGNMENT);
        jTextArea1.setLineWrap(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
